---
- hosts: webservers
  gather_facts: false

  tasks:
    - name: "Iterate through the domains and create certs for each one"
      include_role:
        name: certificates
      with_items: "{{ domains }}"
